---
title: '20170713'
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, root.dir = '/data/nycdoe/')

library(ggplot2)
library(readr)
library(tidyverse)
files <- Sys.glob('/data/nycdoe/June Biog/*.csv')

read_csv_with_year <- function(filename) {
  year <- as.numeric(gsub('-.*$', '', basename(filename)))
  df <- read_csv(filename, col_types = cols(grade_level=col_character(), grade_code=col_character(), admit_code=col_character(), adcode=col_character(),fall_days_present = col_character(), spring_days_present = col_character()))
  df$year <- year
  df
}

```


```{r using bios df}
setwd('/data/nycdoe/')
files <- Sys.glob('/data/nycdoe/June Biog/*.csv')
bios <- map_df(files, read_csv_with_year)
```

##Total number in all years
```{r echo=FALSE}
setwd('/data/nycdoe/')
bios %>% count() 
```

##	Number students per year (This will count students in each year. Students who were there in multiple years are 'counted twice')
```{r, echo=FALSE}
setwd('/data/nycdoe/')
bios %>%
  group_by(year) %>% 
  count() 

```
##plot students per year
```{R,  echo = FALSE}
setwd('/data/nycdoe/')
bios %>% ggplot(aes(x=year)) + geom_histogram()

```

##Number who enter (exit) each year

```{r pressure, echo=FALSE}

bios %>% 
  mutate(enter_year = floor(admit_date/10000)) %>%
  group_by(enter_year) %>% 
  #count() %>% 
  ggplot(aes(x=enter_year)) + geom_histogram(bins = 35) +xlim(2000, 2016)
```
```{R HSAP stuff}
library(ggplot2)
library(readr)
library(tidyverse)
setwd('/data/nycdoe/')


files_HSAPS <- Sys.glob('HSAPS/*.csv')

read_HSAP_Program_codes <- function(filename) {
  year <- as.numeric(substr(filename, 7, 10))
  print(year)
  df <- read_csv(filename, col_types = cols(student_id_scram  = col_character()))
  df$year <- year
  df <- select(df, year, student_id_scram, contains("ProgramCode"))
}
HSAP_Choices <- map_df(files_HSAPS, read_HSAP_Program_codes)

tidy <- HSAP_Choices %>%
  gather(key = "round", value = "school", 3:38) %>%
  mutate(rank= as.integer(substr(round,14,length(round)))) %>%
  mutate(round= as.integer(substr(round,2,2))) 

tidy %>%
  mutate(rank = ifelse(is.na(school), 0 , rank)) %>%
  group_by(student_id_scram)%>%
  filter(rank==max(rank))%>%
  ggplot(aes(x=rank)) + 
  geom_histogram(bins=25)+ 
  labs(x="Number of Choices", y="Number of Students") +
  scale_x_continuous(seq(0,12, by=1),0:12) + facet_wrap(~round)

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
