---
title: "School attendance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readr)
library(tidyverse)
library(dplyr)
library(scales)

#load bio data
files <- Sys.glob('/data/nycdoe/June Biog/*.csv')

read_csv_with_year <- function(filename) {
  year <- as.numeric(gsub('-.*$', '', basename(filename)))
  df <- read_csv(filename, col_types = cols(grade_level=col_character(), grade_code=col_character(), admit_code=col_character(), adcode=col_character(),fall_days_present = col_character(), spring_days_present = col_character()))
  df$year <- year
  df
}

JuneBio <- map_df(files, read_csv_with_year)

bio_data <- JuneBio

#save bio data
save(bio_data, file = "/data/nycdoe/clean_data/bio_data.Rdata")

load("/data/nycdoe/clean_data/bio_data.Rdata")
```

```{r}
days <- bio_data %>% select(student_id_scram, contains("days"), year, dbn, grade_level) 

days_only <-days %>% select(student_id_scram, year, dbn, contains("days"), grade_level )


days_only <- days_only %>% mutate(fall_days_absent = as.numeric(fall_days_absent))

days_only <- days_only %>% mutate(spring_days_absent = as.numeric(spring_days_absent))

days_only <- days_only %>% mutate(spring_days_present = as.numeric(spring_days_present))

days_only <- days_only %>% mutate(fall_days_present = as.numeric(fall_days_present))

days_only <- days_only %>% mutate(days_pres = as.numeric(days_pres))

days_abs_only_df <- days_only %>% select(fall_days_absent, spring_days_absent, days_abs)

days_pres_only_df <- days_only %>% select(fall_days_present, spring_days_present, days_pres)

totalAbsent <- rowSums(days_abs_only_df, na.rm = TRUE)

totalPresent <- rowSums(days_pres_only_df, na.rm = TRUE)

totalAbsent <- data.frame(totalAbsent)
totalPresent <- data.frame(totalPresent)
#############
days_only_summed <- cbind(days_only, totalAbsent, totalPresent)
##############
#all_days <- days_only_summed %>% select(totalPresent, totalAbsent)

#total_School_days <- rowSums(all_days, na.rm = TRUE)

days_only_summed <-  days_only_summed %>% mutate(percentPresent = totalPresent/(totalAbsent + totalPresent))


#days_only_summed <- cbind(days_only_summed, total_School_days)

#get rid of pre-k
days_only_summed  <- days_only_summed %>% mutate(grade_level = ifelse(grade_level == "k", "00", grade_level))

days_only_summed  <- days_only_summed %>% mutate(grade_level = ifelse(grade_level == "pk", "-1", grade_level))

days_only_summed <- days_only_summed %>% mutate(grade_level = as.integer(grade_level))

days_only_summed <- days_only_summed %>% filter(grade_level >= 0 & !is.na(student_id_scram))

#drop students that never showed up (divide by 0)
days_only_summed <- days_only_summed %>% filter(!is.nan(percentPresent))

att_rate_per_school <- days_only_summed %>% group_by(dbn) %>% summarise(avgAtt = mean(percentPresent))

##save this table 
save(att_rate_per_school, file = "/data/nycdoe/clean_data/att_rate_per_school.Rdata")




```

```{r}

att_rate_per_school_per_grade <- days_only_summed %>% group_by(dbn, grade_level) %>% summarise(avgAtt = mean(percentPresent))
save(att_rate_per_school_per_grade, file = "/data/nycdoe/clean_data/att_rate_per_school_per_grade.Rdata")
```


```{r}

#load("/data/nycdoe/clean_data/att_rate.Rdata")

########################
days_only_summed %>% group_by(year, dbn) %>% summarise(maxDays = max(total_School_days))
########################


#2 students have more than 200 days of school recorded!!! get rid of them
days_only_summed <-
days_only_summed %>% filter(totalPresent < 200)

#bio_data %>% filter(student_id_scram == 624232710)

#drop students who never showed to school and never have attendence recorded
days_only_summed <- days_only_summed %>% filter(total_School_days > 0)

SchoolPresRate <- days_only_summed %>% group_by(dbn, year) %>% summarise(presentRate =mean(totalPresent/total_School_days, na.rm = TRUE))

SchoolPresRate <- SchoolPresRate %>% mutate(boro = substr(dbn, 3, 3))
SchoolPresRate <- SchoolPresRate %>% mutate(district = substr(dbn, 1, 2))
SchoolPresRate

SchoolPresRate %>% filter(district<=32) %>% group_by(boro) %>% summarise(attRate = mean(presentRate, na.rm = TRUE))

SchoolPresRate %>% filter(dbn == '01M700')
bio_data %>% filter(dbn == '01M700' )

save(SchoolPresRate, file = "/data/nycdoe/clean_data/att_rate_per_school_with_year.Rdata")
```

```{r}
#save att rate by school
att_rate_per_school <- SchoolPresRate %>% group_by(dbn) %>% summarise(attRate = mean(presentRate, na.rm = TRUE))

att_rate_per_school %>% filter(is.nan(attRate)) #GOOD JOB! no nan's!

bio_data %>% group_by(dbn) %>% summarise()
#######################################
save(att_rate_per_school, file = "/data/nycdoe/clean_data/att_rate_per_school.Rdata")

#save att rate by district

#save att by school

#follow this link for NYC att rate info brken down by boro district and year: Must be opened with IE
# http://schools.nyc.gov/AboutUs/schools/data/stats/arreports.htm

```
#Plot findings
```{r}
days_only_summed %>% ggplot(aes(x= total_School_days)) + geom_histogram()+ scale_y_continuous(labels = comma, limits = c(NA, 1500000))

```
#by boro
```{r}
SchoolPresRate %>% ggplot(aes(x= presentRate)) + geom_histogram()

#days_only_summed %>% ggplot(aes( x = totalPresent)) + geom_histogram()

```

```{r}
SchoolPresRate %>% group_by(dbn) %>% summarise(avg = mean(presentRate, na.rm = TRUE)) %>% ggplot(aes(x = avg)) + geom_histogram()
```

```{r}
#num schools each year (in system)
SchoolPresRate %>% ggplot(aes(x = year)) + geom_histogram()
```

```{r}
SchoolPresRate %>% ggplot(aes(x= year, y = presentRate)) + geom_bar(stat = "identity")

```
# look at one dbn
```{r}
SchoolPresRate %>% filter(dbn == '01M015') %>% ggplot(aes(x = year, y = presentRate)) + geom_bar(stat = "identity")

```
#see averages by boro and year
```{r}
SchoolPresRate %>% group_by(boro, year) %>% summarize (avgAttRate = mean(presentRate, na.rm = TRUE)) %>%  ggplot(aes(x = year, y = avgAttRate)) + geom_bar(stat = "identity") + facet_grid(~boro)

SchoolPresRate %>% filter(year> 2007) %>% group_by(boro) %>% summarise(avgRate = mean(presentRate, na.rm = TRUE))

```
see avgs by year
```{r}
SchoolPresRate %>% group_by(year, dbn) %>% summarise(avgAtt = mean(presentRate, na.rm = TRUE)) %>% ggplot(aes(x = avgAtt)) + geom_histogram() + facet_grid(~year)
```
#Compare to data online
```{r}
#compare to data online by boro
#DOE_att_data <- read.csv("/home/rivka/file.csv")

DOE_att_data <- read_delim("~/file.csv", "\t", escape_double = FALSE, 
    trim_ws = TRUE)


colnames(DOE_att_data)[12] <- "total"

DOE_att_data<- cbind(DOE_att_data, c('M', 'X', 'K', 'Q', 'R', 'all'))

colnames(DOE_att_data)[13] <- "BORO"

boro_att <- SchoolPresRate %>% filter(year> 2007) %>% group_by(boro) %>% summarise(avgRate = mean(presentRate, na.rm = TRUE))

DOE_total_boro <- DOE_att_data %>% select(total, BORO)

DOE_total_boro <- DOE_total_boro %>% filter(BORO != "all")

combo <- inner_join(DOE_total_boro, boro_att, by = c("BORO" = "boro"))

combo %>% ggplot(aes(x = avgRate, y = total)) + geom_point() + geom_abline(intercept = 0, slope = 1)


```

