---
title: "Automated Guidance Counselor - School Features"
author: "Rivka and Ro"
date: "7/20/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readr)
library(tidyverse)
library(dplyr)

files <- Sys.glob('/data/nycdoe/Courses and Grades/*.csv')

read_csv_with_year <- function(filename) {
  year <- as.numeric(gsub('-.*$', '', basename(filename)))
  df <- read_csv(filename, col_types = 
cols(
  student_id = col_integer(),
  grade = col_character(),
  schooldbn = col_character(),
  markingperiod = col_integer(),
  credits = col_double(),
  mark = col_character(),
  alphaequivalent = col_character(),
  numericequivalent = col_integer(),
  passfailequivalent = col_character(),
  subjectcd = col_integer(),
  coursetitle = col_character(),
  gradeaveragefactor = col_double(),
  coresubjectid = col_integer(),
  description = col_character(),
  section = col_integer()
))
  df$year <- year
  df
}

courses_and_grades <- map_df(files[1:10], read_csv_with_year)

course_grades <- courses_and_grades

test <- read_csv_with_year(files[11])

# number of students all years
vec <- vector("list", 11)

for (i in 1:10) {
  df <- read_csv_with_year(files[i])
  vec[[i]] <- df %>%
    select(student_id, grade, schooldbn, coursetitle, description,
           mark, alphaequivalent, numericequivalent, year)
}

vec[[11]] <- test %>%
    select(student_id_scram, grade, schooldbn, coursetitle, description,
           mark, alphaequivalent, numericequivalent, year)


colnames(vec[[11]], student_id_scram = student_id)

dbn_grades <- do.call("rbind", vec)

```

```{r}
View(course_grades)

avg_gpa_by_school <- course_grades %>% 
  group_by(schooldbn,year) %>% filter(!is.na(numericequivalent)) %>%
  summarize(GPA = mean(numericequivalent), student_count = n())

avg_gpa_by_school <- course_grades %>% 
  group_by(schooldbn, student_id, year) %>% filter(!is.na(numericequivalent))

#get only unique students per year

avg_gpa_by_school %>% filter(schooldbn == "	21K525")


save(avg_gpa_by_school, file = "/data/nycdoe/clean_data/gpa_avg_per_school.Rdata")


```
