---
title: "Where Do students go to school?"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(tidyverse)
#library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)

files <- Sys.glob('/data/nycdoe/Zoned DBNs/*.csv')

read_csv_with_year <- function(filename) {
  year <- as.numeric(gsub('-.*$', '', basename(filename)))
  df <- read_csv(filename, col_types = cols(res_zip_cde = col_character(), census_block  = col_character(), census_tract = col_character()))
  df$year <- year
  df
}

zoneData <- map_df(files, read_csv_with_year)

elementary_zoneData <- zoneData %>% filter(!is.na(zoned_elm_dbn))
#records dropped: 152198
nrow(zoneData) - nrow(elementary_zoneData)
middle_zoneData <- zoneData %>% filter(!is.na(zoned_mid_dbn))
nrow(zoneData) - nrow(middle_zoneData)
#records dropped: 154924
hs_zoneData <- zoneData %>% filter(!is.na(zoned_hs_dbn))
nrow(zoneData) - nrow(hs_zoneData)
#records dropped 206430

##################################

files <- Sys.glob('/data/nycdoe/June Biog/*.csv')

read_csv_with_year <- function(filename) {
  year <- as.numeric(gsub('-.*$', '', basename(filename)))
  df <- read_csv(filename, col_types = cols(grade_level=col_character(), grade_code=col_character(), admit_code=col_character(), adcode=col_character(),fall_days_present = col_character(), spring_days_present = col_character()))
  df$year <- year
  df
}

bios <- map_df(files, read_csv_with_year)


```


Join the bio and and zone data for elementary school. This is only from 2015.
```{R}

#elem students merge with bio

elem_year <- elementary_zoneData  #%>% filter(year == 2015)

dbnBioData <- bios %>% 
  select(student_id_scram, dbn, grade_level, year) %>%
  filter(year == 2015)

dbnBioData <-  rename(dbnBioData, BioDbn = dbn)
 
elementary_zone_bio_join <- inner_join(dbnBioData, elem_year, by = "student_id_scram" )

elementary_zone_bio <- elementary_zone_bio_join
```


```{R}
#summarise the grade levels
elementary_zone_bio <- elementary_zone_bio %>% mutate(grade_level = ifelse(grade_level == "0K", "00", grade_level))

# convert grades to integers where 0 = Kindergarten
elementary_zone_bio <- elementary_zone_bio %>% mutate(grade_level = as.integer(grade_level)) %>%
  filter(!is.na(grade_level)) 

elementary_zone_bio <- elementary_zone_bio %>% filter(grade_level<6) %>% select(year.x, BioDbn, zoned_elm_dbn, student_id_scram, grade_level)


elem_zone_tidy <- elementary_zone_bio %>% select(student_id_scram, zoned_elm_dbn, BioDbn, grade_level)

#percent of people that go to their zoned schools

```

```{r}
# match on zoned school and bio
elem_zone_tidy %>% mutate(match_dbn = ifelse(zoned_elm_dbn == BioDbn, 1, 0)) %>% 
  group_by(match_dbn) %>% summarise(count = n())

# group by grade and get counts of matches by grade
elem_zone_tidy %>% mutate(match_dbn = ifelse(zoned_elm_dbn == BioDbn, 1, 0)) %>% 
  group_by(grade_level, match_dbn) %>% summarise(count = n())


match_df <- elem_zone_tidy %>% mutate(match_dbn = ifelse(zoned_elm_dbn == BioDbn, 1, 0))

```

```{r}

# some dbns don't have a 0 boro and the dbn is in not in standard dbn format
match_df %>% filter(match_dbn == 0) %>% mutate(zoned_boro = substr(zoned_elm_dbn, 3,3)) #%>% 
  group_by(zoned_boro) %>% summarise(count = n())
  
# 69974 have a zoned boro of zero, 168331 have a standard zoned boro
match_df %>% filter(match_dbn == 0) %>% mutate(zoned_boro = substr(zoned_elm_dbn, 3,3)) %>%
  mutate(to_boro = substr(BioDbn, 3, 3)) %>% group_by(zoned_boro == 0) %>% summarise(count = n())

# count of students who went to 
match_df %>% filter(match_dbn == 0) %>% mutate(zoned_boro = substr(zoned_elm_dbn, 3,3)) %>%
  mutate(to_boro = substr(BioDbn, 3, 3))

# number of students zoned to a school
match_df %>% group_by(zoned_elm_dbn) %>% summarise(zoned_to_dbn = n())

# number of studebts who went to a specific school
local_zones_data <- full_join( (match_df %>% group_by(zoned_elm_dbn) %>% summarise(zoned_to_dbn = n())), 
            (match_df %>% group_by(BioDbn) %>% summarise(went_to_dbn = n())),
           by = c("zoned_elm_dbn" = "BioDbn") )

local_zones_data <- full_join( local_zones_data, 
           (match_df %>% filter(match_dbn == 1) %>% group_by(zoned_elm_dbn) %>% 
   summarise(attending_zoned_dbn = n())),
   by = "zoned_elm_dbn")

local_zones_data <- local_zones_data %>% mutate(perc_local = (attending_zoned_dbn/went_to_dbn)*100)
local_zones_data %>% mutate(boro = substr(zoned_elm_dbn, 3, 3)) %>% filter(!is.na(attending_zoned_dbn)) %>% group_by(boro) %>% summarize(sum_attended_zoned=sum(attending_zoned_dbn), sum_zoned= sum(zoned_to_dbn)) %>%
  mutate(perc_boro_att_zoned = (sum_attended_zoned/sum_zoned)*100)

local_zones_data
```

```{R}

```