---
title: "Map of Feeder Schools"
author: "Rivka and Ro"
date: "7/27/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load files

```{r}

# shape file for school zones
hs_zones <- GET("https://data.cityofnewyork.us/api/geospatial/j4gs-ge7j?method=export&format=GeoJSON")
hs_dbns <- readOGR(content(hs_zones,'text'), 'OGRGeoJSON', verbose = F)

load("/data/nycdoe/clean_data/where_students_go_feeder_year.Rdata")
feeder_data <- where_students_go_feeder_data_year

#load lat lonngs and census tract for school
load("/data/nycdoe/school_info_with_lat_long.Rdata")

load("/data/nycdoe/")

```

```{r}

#think about: computing distance for how for a student travels for schools

# number of closed schools = zero
school_info %>% select(`ATS System Code`, `Location Code`, `Location Name`, `Managed By Name`, `Location Category Description`,  `Census Tract`) %>% group_by(`Status Description`) %>% summarise()


# df to join later on dbn to add census tract for dbn and the school name
school_info_join <- school_info %>% 
  select(`ATS System Code`, `Location Name`, `Location Category Description`, `Census Tract`)
# fix names of columns
school_info_join <- school_info_join %>% 
  rename(ats_system_code = `ATS System Code`, 
         location_name = `Location Name`, 
         loc_category_descr = `Location Category Description`, 
         school_census_tract = `Census Tract`)
# change census tract to 6 digits
school_info_join <- school_info_join %>% 
  ungroup() %>% 
  mutate(school_census_tract = as.integer(school_census_tract))
school_info_join <- school_info_join %>%
  mutate(school_census_tract =  sprintf("%06d", school_census_tract))
school_info_join <- school_info_join %>%
  mutate(school_census_tract = as.character(school_census_tract))

# df with latitude and longitude for each school
schools_lat_long <- lat_long

```


### data frames for middle school and high school
```{r}

mid_to_hs <- feeder_data

hs_to_mid <- feeder_data %>% select(hs_dbn, mid_dbn, year, count) %>% arrange(hs_dbn)

```


### joining data frames for mapping
```{r}

# joining the lat long and school info dfs
lat_long_and_school_info <- inner_join(school_info_join, schools_lat_long, by = c("ats_system_code" = "dbn"))

# join above data frame (lat long for school) with mid to hs and hs to mid dfs

##### middle to high school (mapping what high schools students go to)
mid_to_hs <- inner_join(mid_to_hs, lat_long_and_school_info, by = c("hs_dbn" = "ats_system_code"))
##### high school to middle school (mapping what middle schools students come from)
hs_to_mid <- inner_join(hs_to_mid, lat_long_and_school_info, by =c("mid_dbn" = "ats_system_code"))


```

### mapping mid_to_hs and hs_to_mid to a map of census tracts
```{r}

# load nyc census tracts file = nyc_tracts
load("/data/nycdoe/nyc_tracts.Rdata")

# sample middle school map data
sample_ms_map_data <- mid_to_hs %>% filter(mid_dbn == "10X368" & year == 2012)

# sample hs map data
sample_hs_map_data <- hs_to_mid %>% filter(hs_dbn == "01M292", year == 2010)

# middle school map merge
ms_map <- merge(nyc_tracts, sample_ms_map_data, by.x="TRACTCE", by.y = "school_census_tract")

# high school map merge
hs_map <- merge(nyc_tracts, sample_hs_map_data, by.x="TRACTCE", by.y = "school_census_tract")

```


## creating middle school map
## when a middle school is chosen, the map will show which census tract and which high schools students are going to
```{r}


#palette for plotting map
pal <- colorNumeric(palette = "Reds",
                    domain = range(ms_map@data$count, na.rm=T), na.color="transparent")

#create icons for middle and high schools
mid_school_icon <- makeIcon(
  iconUrl = "https://cdn2.iconfinder.com/data/icons/buildings-6/90/01-512.png",
  iconWidth = 30, iconHeight = 30
)

hs_school_icon <- makeIcon(
  iconUrl = "http://www.freeiconspng.com/uploads/high-school-icon-png-8.png",
  iconWidth = 30, iconHeight = 30
)

leaflet(ms_map) %>%
  #addTiles() %>% 
  addPolygons(weight = .5, color="#a5a5a5", fillColor = ~pal(count), popup = ~paste("Number of Students:", count, "</br>School Name:", location_name), fillOpacity = .7) %>% 
  addLegend(pal = pal, values = ~count, opacity = 1) %>%
  addMarkers(~lon, ~lat, popup = ~as.factor(hs_dbn), label = ~location_name, icon = hs_school_icon) %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-73.98, 40.75, zoom = 13)


```

### high school to middle school
```{r}

hs_to_mid <- where_students_go_feeder_data_year %>% select(hs_dbn, mid_dbn, year, count) %>% arrange(hs_dbn)

```

### function for map from high school to middle school
```{r, echo=FALSE}}

ms_zones <- GET("https://data.cityofnewyork.us/api/geospatial/awbp-qqq3?method=export&format=GeoJSON")
ms_dbns <- readOGR(content(ms_zones,'text'), 'OGRGeoJSON', verbose = F)

hs_to_mid <- hs_to_mid %>% ungroup() %>% mutate(mid_dbn = as.factor(mid_dbn), hs_dbn = as.factor(hs_dbn))

hs_to_mid <- hs_to_mid %>% filter(hs_dbn == "10X368", year == 2009)

ms_map <- merge(ms_dbns, hs_to_mid, by.x = "dbn", by.y = "mid_dbn")

#doesn't exist for stuyvesant or brooklyn latin
pal <- colorNumeric(palette = "Reds",
                    domain = range(ms_map@data$count, na.rm=T))

  leaflet(ms_map) %>%
    #addTiles() %>% 
    addPolygons(weight = .5, fillColor = ~pal(count), popup = ~paste("Number of Students:", count, "</br>School Code:", dbn), fillOpacity = .7) %>% 
    addLegend(pal = pal, values = ~count, opacity = 1, 
              title = "<p>Where Students come from </br> to a High School</p>") %>%
     #addMarkers(~-73.85887472057718, ~40.849304131586, popup = ~as.factor(hs_dbn), label = ~hs_dbn, icon = school_icon) #%>%
    addProviderTiles("CartoDB.Positron") %>%
    setView(-73.98, 40.75, zoom = 13)


############## Function to get map ###############

map_hs_to_mid <- function(high_school, school_year) {
  
  hs_to_mid <- hs_to_mid %>% filter(hs_dbn == high_school & year == school_year)
  
  ms_map <- merge(ms_dbns, hs_to_mid, by.x = "dbn", by.y = "mid_dbn")

  #plot map
  pal <- colorNumeric(palette = "Reds",
                    domain = range(ms_map@data$count, na.rm=T))

  leaflet(ms_map) %>%
    #addTiles() %>% 
    addPolygons(weight = .5, fillColor = ~pal(count), popup = ~paste("Number of Students:", count, "</br>School Code:", dbn), fillOpacity = .7) %>% 
    addLegend(pal = pal, values = ~count, opacity = 1, 
              title = "<p>Where Students come from </br> to a High School</p>") %>%
     #addMarkers(~-73.85887472057718, ~40.849304131586, popup = ~as.factor(hs_dbn), label = ~hs_dbn, icon = school_icon) #%>%
    addProviderTiles("CartoDB.Positron") %>%
    setView(-73.98, 40.75, zoom = 13)

}

# issue, not every school comes up
map_hs_to_mid("10X368", 2009)


```